// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import Sidebar from "../../components/sidebar";
import Header from "../../components/header";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <html lang="en">
      // <body>      
        <div className="layout-grid-container">
          <div className="header">
            <Header />
          </div>
          <div className="sidebar">
            <Sidebar />
          </div>
          <div className="mainLayout-children-container">
            {children}
          </div>
        </div>
      // </body>
    // </html>
  );
}
